### ISSUE TITLE
Couldn't find translation key

### ISSUE THREAD

**Issue by lisandi** [citizenos/ep_foot_note#1]
We receive the following Error Messages in Chrome on Mac OSX with the newest versions of Etherpad (installed yesterday from Github)

Couldn't find translation key ep_foot_note.toolbar.add_foot_note.title
html10n.translateNode @ html10n.js?v=871e115c:1

**Comment by ilmartyrk** [comment]
@lisandi is this issue still relevant? Closing as I couldn't replicate
