### ISSUE TITLE
There is no FN Button/Menu Item visible

### ISSUE THREAD

**Issue by lisandi** [citizenos/ep_foot_note#2]
We installed the plugin but honestly can't find that FN Button or Menu Item.
![Screen Shot 2021-09-25 at 23 16 21](https://user-images.githubusercontent.com/1982011/134778357-7026162f-5149-4575-98b2-b412dd59a671.png)
Where should that button be?

**Comment by ilmartyrk** [comment]
This issue should be fixed, the button has asterix icon, you can change the position from your etherpads settings.json file. under toolbar. Button name is "addFootNote"
